@Server_HostAddress = https://localhost:7220

GET {{Server_HostAddress}}/weatherforecast/
Accept: application/json

### SendPayload1
POST {{Server_HostAddress}}/photos
Content-Type: application/json

< ./input1.json